# Generated by Django 6.0.6 on 2026-07-02 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('platform', models.CharField(choices=[('shopify', 'Shopify'), ('wordpress', 'WordPress'), ('webflow', 'Webflow'), ('custom', 'Custom')], default='shopify', max_length=20)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('pages_total', models.IntegerField(default=0)),
                ('pages_done', models.IntegerField(default=0)),
                ('chunks_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_jobs', to='websites.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('html', models.TextField()),
                ('clean_text', models.TextField()),
                ('page_type', models.CharField(choices=[('faq', 'FAQ'), ('about', 'About'), ('shipping', 'Shipping'), ('contact', 'Contact'), ('product', 'Product'), ('blog', 'Blog'), ('other', 'Other')], default='other', max_length=20)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawled', 'Crawled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='websites.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('merchant', 'url'), name='unique_merchant_website'),
        ),
    ]
