# Generated by Django 6.0.6 on 2026-07-15 21:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_source_type(apps, schema_editor):
    KnowledgeChunk = apps.get_model('websites', 'KnowledgeChunk')
    KnowledgeChunk.objects.filter(source_type='scraped').update(source_type='page')


def reverse_backfill(apps, schema_editor):
    KnowledgeChunk = apps.get_model('websites', 'KnowledgeChunk')
    KnowledgeChunk.objects.filter(source_type='page').update(source_type='scraped')


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('websites', '0002_knowledgechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='integrations.product'),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='websites.crawledpage'),
        ),
        migrations.RunPython(backfill_source_type, reverse_backfill),
    ]