# Generated by Django 6.0.6 on 2026-07-02 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(choices=[('answer', 'Answer'), ('missing_content', 'Missing Content'), ('outdated_content', 'Outdated Content'), ('improve_page', 'Improve Page')], default='answer', max_length=20)),
                ('context', models.TextField()),
                ('recommendation', models.TextField()),
                ('reason', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('fallback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='chat.fallbackticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
