# Generated by Django 6.0.6 on 2026-07-08 08:32

from django.db import migrations, models
def migrate_old_statuses(apps, schema_editor):
    FallbackTicket = apps.get_model('chat', 'FallbackTicket')
    FallbackTicket.objects.filter(ticket_status='open').update(ticket_status='new')
    FallbackTicket.objects.filter(ticket_status='resolved').update(ticket_status='closed')


def reverse_migrate_old_statuses(apps, schema_editor):
    FallbackTicket = apps.get_model('chat', 'FallbackTicket')
    FallbackTicket.objects.filter(ticket_status='new').update(ticket_status='open')
    FallbackTicket.objects.filter(ticket_status='closed').update(ticket_status='resolved')


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallbackticket',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fallbackticket',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fallbackticket',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='fallbackticket',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fallbackticket',
            name='ticket_status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('awaiting_customer', 'Awaiting Customer'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.RunPython(migrate_old_statuses, reverse_migrate_old_statuses),
    ]
