# Generated by Django 6.0.6 on 2026-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_fallbackticket_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
