# Generated by Django 6.0.6 on 2026-07-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='notify_on_escalation',
            field=models.BooleanField(default=True),
        ),
    ]
